language: java

jdk:
    - oraclejdk8

sudo: false

before_script:
    - cd jyhton
    - export INSTALLATION_ROOT="."
    - uname -a
    - printenv

script:
    - pwd
    - ant
    - ant

after_script:
    - dist/bin/jython nativeSIMunitTests.py

